name: "ehr_interoperability_analytics_pipeline"
version: "1.0.0"
config-version: 2

profile: "ehr_interoperability_analytics_pipeline"

model-paths: ["models"]
target-path: "target"
clean-targets:
  - "target"
  - "dbt_packages"

models:
  ehr_interoperability_analytics_pipeline:
    +materialized: view
    staging:
      +schema: analytics
    marts:
      +materialized: table
      +schema: analytics
